<?php

use yii\helpers\Html;
use \dmstr\bootstrap\Tabs;
use yii\jui\DatePicker;
use yii\bootstrap\ActiveForm;


/**
* @var yii\web\View $this
* @var backend\modules\crud\models\Icsr $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="icsr-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Icsr',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                         Html::activeHiddenInput($model, 'drug_id') ;
   
 ; ?>
			<?php echo $form->field($model, 'patient_identifier')->textInput(['maxlength' => true]) ?>
			<?php echo $form->field($model, 'patient_age')->textInput(['maxlength' => true]) ?>
			<?php echo                         $form->field($model, 'patient_age_unit')->dropDownList(
                            backend\modules\crud\models\Icsr::optspatientageunit()
                        ); ?>
			<?php echo $form->field($model, 'patient_birth_date')->widget(DatePicker::className(),['dateFormat' => 'yyyy-MM-dd']); ?>
			<?php echo $form->field($model, 'patient_weight')->textInput(['maxlength' => true]) ?>
			<?php echo $form->field($model, 'patient_weight_unit')->dropDownList(
                            backend\modules\crud\models\Icsr::optspatientweightunit()
                        ); ?>
			<?php echo $form->field($model, 'extra_history')->textArea(['maxlength' => true]) ;?>
			<?=                         $form->field($model, 'is_serious')->dropDownList(
                            backend\modules\crud\models\Icsr::optsisserious()
                        ); ?>
			<?=                         $form->field($model, 'results_in_death')->dropDownList(
                            backend\modules\crud\models\Icsr::optsresultsindeath()
                        ); ?>
			<?=                         $form->field($model, 'life_threatening')->dropDownList(
                            backend\modules\crud\models\Icsr::optslifethreatening()
                        ); ?>
			<?=                         $form->field($model, 'requires_hospitalization')->dropDownList(
                            backend\modules\crud\models\Icsr::optsrequireshospitalization()
                        ); ?>
			<?=                         $form->field($model, 'results_in_disability')->dropDownList(
                            backend\modules\crud\models\Icsr::optsresultsindisability()
                        ); ?>
			<?=                         $form->field($model, 'is_congenital_anomaly')->dropDownList(
                            backend\modules\crud\models\Icsr::optsiscongenitalanomaly()
                        ); ?>
			<?=                         $form->field($model, 'others_significant')->dropDownList(
                            backend\modules\crud\models\Icsr::optsotherssignificant()
                        ); ?>
			<?=                         $form->field($model, 'report_type')->dropDownList(
                            backend\modules\crud\models\Icsr::optsreporttype()
                        ); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'reaction_country_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\modules\crud\models\LkpCountry::find()->all(), 'id', 'name'),
    ['prompt' => Yii::t('app', 'Select')]
); ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => $model->getAliasModel(),
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

