<?php
/**
 * /var/www/html/yiiyak/console/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
 

use \dmstr\bootstrap\Tabs;
use yii\jui\DatePicker;
use yii\bootstrap\ActiveForm;

/**
 *
 * @var yii\web\View $this
 * @var backend\modules\crud\models\Icsr $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="icsr-form">

    <?php $form = ActiveForm::begin([
		'id' => 'Icsr',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-error'
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

			<?php echo // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                         Html::activeHiddenInput($model, 'drug_id') ;
   
 ; ?>
			<?php echo $form->field($model, 'patient_identifier')->textInput(['maxlength' => true]) ?>
			<?php echo $form->field($model, 'patient_age')->textInput(['maxlength' => true]) ?>
			<?php echo                         $form->field($model, 'patient_age_unit')->dropDownList(
	backend\modules\crud\models\Icsr::optspatientageunit()
); ?>
			<?php echo $form->field($model, 'patient_birth_date')->widget(DatePicker::className(),['dateFormat' => 'yyyy-MM-dd']); ?>
			<?php echo $form->field($model, 'patient_weight')->textInput(['maxlength' => true]) ?>
			<?php echo $form->field($model, 'patient_weight_unit')->dropDownList(
	backend\modules\crud\models\Icsr::optspatientweightunit()
); ?>
			<?php echo $form->field($model, 'extra_history')->textArea(['maxlength' => true]) ;
                                 ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [ [
				'label'   => $model->getAliasModel(),
				'content' => $this->blocks['main'],
				'active'  => true,
			], ]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
