<?php
return [
    'adminEmail' => 'admin@example.com',
    'gaId' => '\'UA-83150001-1\'',


    'e2bLkp' => [
                    'ichicsrmessageheader' => ['title' => 'ICH ICSR Message Header' , 'element' => 'M.1'],
                    'safetyreport' => ['title' => 'Identification of the case safety report' , 'element' => 'A.1'],
                    'messagetype' => ['title' => '' , 'element' => ''],
                    'messageformatversion' => ['title' => '' , 'element' => ''],
                    'messageformatrelease' => ['title' => '' , 'element' => ''],
                    'messagenumb' => ['title' => '' , 'element' => ''],
                    'messagesenderidentifier' => ['title' => '' , 'element' => ''],
                    'messagereceiveridentifier' => ['title' => '' , 'element' => ''],
                    'messagedateformat' => ['title' => '' , 'element' => ''],
                    'messagedate' => ['title' => '' , 'element' => ''],
                    'safetyreportid' => ['title' => '' , 'element' => ''],
                    'primarysourcecountry' => ['title' => '' , 'element' => ''],
                    'reporttype' => ['title' => '' , 'element' => ''],
                    'serious' => ['title' => '' , 'element' => ''],
                    'seriousnessdeath' => ['title' => '' , 'element' => ''],
                    'seriousnesslifethreatening' => ['title' => '' , 'element' => ''],
                    'seriousnesshospitalization' => ['title' => '' , 'element' => ''],
                    'seriousnessdisabling' => ['title' => '' , 'element' => ''],
                    'seriousnesscongenitalanomali' => ['title' => '' , 'element' => ''],
                    'seriousnessother' => ['title' => '' , 'element' => ''],
                    'receivedateformat' => ['title' => '' , 'element' => ''],
                    'receivedate' => ['title' => '' , 'element' => ''],
                    'receiptdateformat' => ['title' => '' , 'element' => ''],
                    'receiptdate' => ['title' => '' , 'element' => ''],
                    'authoritynumb' => ['title' => '' , 'element' => ''],
                    'primarysource' => ['title' => '' , 'element' => ''],
                    'qualification' => ['title' => '' , 'element' => ''],
                    'sender' => ['title' => '' , 'element' => ''],
                    'sendertype' => ['title' => '' , 'element' => ''],
                    'senderorganization' => ['title' => '' , 'element' => ''],
                    'senderemailaddress' => ['title' => '' , 'element' => ''],
                    'receiver' => ['title' => '' , 'element' => ''],
                    'patient' => ['title' => '' , 'element' => ''],
                    'patientbirthdateformat' => ['title' => '' , 'element' => ''],
                    'patientbirthdate' => ['title' => '' , 'element' => ''],
                    'patientonsetage' => ['title' => '' , 'element' => ''],
                    'patientonsetageunit' => ['title' => '' , 'element' => ''],
                    'patientweight' => ['title' => '' , 'element' => ''],
                    'patientmedicalhistorytext' => ['title' => '' , 'element' => ''],
                    'reaction' => ['title' => '' , 'element' => ''],
                    'primarysourcereaction' => ['title' => '' , 'element' => ''],
                    'reactionmeddraversionllt' => ['title' => '' , 'element' => ''],
                    'reactionmeddrallt' => ['title' => '' , 'element' => ''],
                    'reactionstartdateformat' => ['title' => '' , 'element' => ''],
                    'reactionstartdate' => ['title' => '' , 'element' => ''],
                    'reactionenddateformat' => ['title' => '' , 'element' => ''],
                    'reactionenddate' => ['title' => '' , 'element' => ''],
                    'reactionoutcome' => ['title' => '' , 'element' => ''],
                    'drug' => ['title' => '' , 'element' => ''],
                    'drugcharacterization' => ['title' => '' , 'element' => ''],
                    'medicinalproduct' => ['title' => '' , 'element' => ''],
                    'summary' => ['title' => '' , 'element' => ''],
                    'narrativeincludeclinical' => ['title' => '' , 'element' => ''],

    ]
];
