<?php
return [
    'adminEmail' => 'admin@example.com',
    'gaId' => '\'UA-83150001-1\'',


    'e2bLkp' => [
                    'ichicsrmessageheader' => ['title' => 'ICH ICSR Message Header' , 'element' => 'M.1'],
                    'safetyreport' => ['title' => 'Identification of the case safety report' , 'element' => 'A.1'],
                    'messagetype' => ['title' => 'Message Type' , 'element' => 'M.1.1'],
                    'messageformatversion' => ['title' => 'Message Format Version' , 'element' => 'M.1.2'],
                    'messageformatrelease' => ['title' => 'Message Format Release' , 'element' => 'M.1.3'],
                    'messagenumb' => ['title' => 'Message Number' , 'element' => 'M.1.4'],
                    'messagesenderidentifier' => ['title' => 'Message Sender Identifier' , 'element' => 'M.1.5'],
                    'messagereceiveridentifier' => ['title' => 'Message Receiver Identifier' , 'element' => 'M.1.6'],
                    'messagedateformat' => ['title' => 'Message Date Format' , 'element' => 'M.1.7a'],
                    'messagedate' => ['title' => 'Message Date' , 'element' => 'M.1.7b'],
                    'safetyreportid' => ['title' => 'Sender\'s (Case) Safety Report Unique Identifier' , 'element' => 'A.1.0.1'],
                    'primarysourcecountry' => ['title' => 'Identification of the country of the primary' , 'element' => 'A.1.1'],
                    'reporttype' => ['title' => 'Type of report 1=Spontaneous , 2=Report from study ,3=Other ,4=Not available to sender' , 'element' => 'A.1.4'],
                    'serious' => ['title' => 'Serious 1=Yes 2=No' , 'element' => 'A.1.5.1'],
                    'seriousnessdeath' => ['title' => 'Results in death 1=Yes 2=No' , 'element' => 'A.1.5.2'],
                    'seriousnesslifethreatening' => ['title' => 'Life threatening 1=Yes 2=No' , 'element' => 'A.1.5.2'],
                    'seriousnesshospitalization' => ['title' => 'Caused/prolonged 1=Yes 2=No' , 'element' => 'A.1.5.2'],
                    'seriousnessdisabling' => ['title' => 'Disabling/Incapacitating 1=Yes 2=No' , 'element' => 'A.1.5.2'],
                    'seriousnesscongenitalanomali' => ['title' => 'Congenital anomaly/birth defect 1=Yes 2=No' , 'element' => 'A.1.5.2'],
                    'seriousnessother' => ['title' => 'Other medically important condition 1=Yes 2=No' , 'element' => 'A.1.5.2'],
                    'receivedateformat' => ['title' => 'Date 102 - Format CCYYMMDD' , 'element' => 'A.1.6a'],
                    'receivedate' => ['title' => 'Date report was first received from source' , 'element' => 'A.1.6b'],
                    'receiptdateformat' => ['title' => 'Date 102 - Format CCYYMMDD' , 'element' => 'A.1.7a'],
                    'receiptdate' => ['title' => 'Date of receipt of the most recent information for this report' , 'element' => 'A.1.7b'],
                    'authoritynumb' => ['title' => 'Regulatory authority\'s case report number' , 'element' => 'A.1.10.1'],
                    'primarysource' => ['title' => 'Primary source(s) of information' , 'element' => 'A.2'],
                    'qualification' => ['title' => "Qualification <br> 1=Physician <br> 2=Pharmacist  <br> 3=Other Health Professional <br> 4=Lawyer <br> 5=Consumer or other non health professional" , 'element' => 'A.2.1.4'],
                    'sender' => ['title' => 'Information on Header Sender and Receiver of Case Safety Report' , 'element' => 'A.3'],
                    'sendertype' => ['title' => "1=Pharmaceutical <br> 2=Regulatory Authority <br>3=Health professional<br>4=Regional Pharmacovigilance Center<br>5=WHO Collaborating Center for International Drug Monitoring<br>6=Other" , 'element' => 'A.3.1.1'],
                    'senderorganization' => ['title' => 'Sender Identifier' , 'element' => 'A.3.1.2'],
                    'senderemailaddress' => ['title' => 'Sender\'s E-mail Address' , 'element' => 'A.3.1.4l'],
                    'receiver' => ['title' => 'Receiver' , 'element' => 'A.3.2'],
                    'patient' => ['title' => 'Patient characteristics' , 'element' => 'B.1'],
                    'patientbirthdateformat' => ['title' => 'Date 102 - Format CCYYMMDD' , 'element' => 'B.1.2.1a'],
                    'patientbirthdate' => ['title' => 'Date of birth' , 'element' => 'B.1.2.1b'],
                    'patientonsetage' => ['title' => 'Age at time of onset of reaction/event' , 'element' => 'B.1.2.2a'],
                    'patientonsetageunit' => ['title' => '800 = Decade<br>801=Year<br>802=Month<br>803=Week<br>804=Day<br>805=Hour' , 'element' => 'B.1.2.2b'],
                    'patientweight' => ['title' => 'Weight (kg)' , 'element' => 'B.1.3'],
                    'patientmedicalhistorytext' => ['title' => 'Text for relevant medical history and concurrent conditions' , 'element' => 'B.1.7.2'],
                    'reaction' => ['title' => 'Reaction(s)/Event(s)' , 'element' => 'B.2'],
                    'primarysourcereaction' => ['title' => 'Reaction/event as reported by primary source' , 'element' => 'B.2.i.0'],
                    'reactionmeddraversionllt' => ['title' => 'MedDRA version for reaction/event term LLT' , 'element' => 'B.2.i.1.a'],
                    'reactionmeddrallt' => ['title' => 'Reaction/event in MedDRA terminology (LLT)' , 'element' => 'B.2.i.1.b'],
                    'reactionstartdateformat' => ['title' => '102 - Format CCYYMMDD <br>203 - Format CYYMMDDHHMM <br> 610 - Format CCYYMM <br>602 - Format CCYY' , 'element' => 'B.2.i.4a'],
                    'reactionstartdate' => ['title' => 'Date of start of reaction/event' , 'element' => 'B.2.i.4b'],
                    'reactionenddateformat' => ['title' => '102 - Format CCYYMMDD <br>203 - Format CYYMMDDHHMM <br> 610 - Format CCYYMM <br>602 - Format CCYY' , 'element' => 'B.2.i.5a'],
                    'reactionenddate' => ['title' => 'Date of end of reaction/event' , 'element' => 'B.2.i.5b'],
                    'reactionoutcome' => ['title' => '1=recovered/resolved<br> 2=recovering/resolving<br> 3=not recovered/not resolved <br> 4=recovered/resolved with sequelae<br> 5=fatal <br> 6=unknown' , 'element' => 'B.2.i.8'],
                    'drug' => ['title' => 'Drug(s) Information' , 'element' => 'B.4'],
                    'drugcharacterization' => ['title' => '1=Suspect<br>2=Concomitant<br>3=Interacting' , 'element' => 'B.4.k.1'],
                    'medicinalproduct' => ['title' => 'Characterization of drug role' , 'element' => 'B.4.k.2.1'],
                    'summary' => ['title' => 'Narrative case summary and further information' , 'element' => 'B.5'],
                    'narrativeincludeclinical' => ['title' => 'Case narrative including clinical course,<br> therapeutic measures, outcome and additional relevant information' , 'element' => 'B.5.1'],

    ]
];
