<?php
return [
    'adminEmail' => 'admin@example.com',
    'gaId' => '\'UA-83150001-1\'',
    'ich' => 'http://estri.ich.org/e2br22/index.htm',
    'dtd' => 'http://estri.ich.org/e2br22/ich-icsrack-v1_1_dtd.zip',

    'e2bLkp' => [
        'ichicsrmessageheader' => ['title' => 'ICH ICSR Message Header' , 'element' => 'M.1'],
        'safetyreport' => ['title' => 'Identification of the case safety report' , 'element' => 'A.1'],
        'messagetype' => ['title' => 'Message Type' , 'element' => 'M.1.1'],
        'messageformatversion' => ['title' => 'Message Format Version' , 'element' => 'M.1.2'],
        'messageformatrelease' => ['title' => 'Message Format Release' , 'element' => 'M.1.3'],
        'messagenumb' => ['title' => 'Message Number' , 'element' => 'M.1.4'],
        'messagesenderidentifier' => ['title' => 'Message Sender Identifier' , 'element' => 'M.1.5'],
        'messagereceiveridentifier' => ['title' => 'Message Receiver Identifier' , 'element' => 'M.1.6'],
        'messagedateformat' => ['title' => 'Message Date Format' , 'element' => 'M.1.7a'],
        'messagedate' => ['title' => 'Message Date' , 'element' => 'M.1.7b'],
        'safetyreportid' => ['title' => 'Sender\'s (Case) Safety Report Unique Identifier' , 'element' => 'A.1.0.1'],
        'primarysourcecountry' => ['title' => 'Identification of the country of the primary' , 'element' => 'A.1.1'],
        'reporttype' => ['title' => 'Type of report ' , 'element' => 'A.1.4'],
        'serious' => ['title' => 'Serious ' , 'element' => 'A.1.5.1'],
        'seriousnessdeath' => ['title' => 'Results in death  ' , 'element' => 'A.1.5.2'],
        'seriousnesslifethreatening' => ['title' => 'Life threatening  ' , 'element' => 'A.1.5.2'],
        'seriousnesshospitalization' => ['title' => 'Caused/prolonged  ' , 'element' => 'A.1.5.2'],
        'seriousnessdisabling' => ['title' => 'Disabling/Incapacitating  ' , 'element' => 'A.1.5.2'],
        'seriousnesscongenitalanomali' => ['title' => 'Congenital anomaly/birth defect  ' , 'element' => 'A.1.5.2'],
        'seriousnessother' => ['title' => 'Other medically important condition ' , 'element' => 'A.1.5.2'],
        'receivedateformat' => ['title' => 'Date 102 - Format CCYYMMDD' , 'element' => 'A.1.6a'],
        'receivedate' => ['title' => 'Date report was first received from source' , 'element' => 'A.1.6b'],
        'receiptdateformat' => ['title' => 'Date 102 - Format CCYYMMDD' , 'element' => 'A.1.7a'],
        'receiptdate' => ['title' => 'Date of receipt of the most recent information for this report' , 'element' => 'A.1.7b'],
        'authoritynumb' => ['title' => 'Regulatory authority\'s case report number' , 'element' => 'A.1.10.1'],
        'primarysource' => ['title' => 'Primary source(s) of information' , 'element' => 'A.2'],
        'qualification' => ['title' => "Qualification " , 'element' => 'A.2.1.4'],
        'sender' => ['title' => 'Information on Header Sender and Receiver of Case Safety Report' , 'element' => 'A.3'],
        'sendertype' => ['title' => "Sender Type" , 'element' => 'A.3.1.1'],
        'senderorganization' => ['title' => 'Sender Identifier' , 'element' => 'A.3.1.2'],
        'senderemailaddress' => ['title' => 'Sender\'s E-mail Address' , 'element' => 'A.3.1.4l'],
        'receiver' => ['title' => 'Receiver' , 'element' => 'A.3.2'],
        'patient' => ['title' => 'Patient characteristics' , 'element' => 'B.1'],
        'patientbirthdateformat' => ['title' => 'Date 102 - Format CCYYMMDD' , 'element' => 'B.1.2.1a'],
        'patientbirthdate' => ['title' => 'Date of birth' , 'element' => 'B.1.2.1b'],
        'patientonsetage' => ['title' => 'Age at time of onset of reaction/event' , 'element' => 'B.1.2.2a'],
        'patientonsetageunit' => ['title' => 'Age Unit' , 'element' => 'B.1.2.2b'],
        'patientweight' => ['title' => 'Weight (kg)' , 'element' => 'B.1.3'],
        'patientmedicalhistorytext' => ['title' => 'Text for relevant medical history and concurrent conditions' , 'element' => 'B.1.7.2'],
        'reaction' => ['title' => 'Reaction(s)/Event(s)' , 'element' => 'B.2'],
        'primarysourcereaction' => ['title' => 'Reaction/event as reported by primary source' , 'element' => 'B.2.i.0'],
        'reactionmeddraversionllt' => ['title' => 'MedDRA version for reaction/event term LLT' , 'element' => 'B.2.i.1.a'],
        'reactionmeddrallt' => ['title' => 'Reaction/event in MedDRA terminology (LLT)' , 'element' => 'B.2.i.1.b'],
        'reactionstartdateformat' => ['title' => 'Reaction Start Date Format' , 'element' => 'B.2.i.4a'],
        'reactionstartdate' => ['title' => 'Date of start of reaction/event' , 'element' => 'B.2.i.4b'],
        'reactionenddateformat' => ['title' => 'Reaction End Date Format' , 'element' => 'B.2.i.5a'],
        'reactionenddate' => ['title' => 'Date of end of reaction/event' , 'element' => 'B.2.i.5b'],
        'reactionoutcome' => ['title' => 'Outcome of reaction/event at the time of last observation' , 'element' => 'B.2.i.8'],
        'drug' => ['title' => 'Drug(s) Information' , 'element' => 'B.4'],
        'drugcharacterization' => ['title' => 'Characterization of drug role' , 'element' => 'B.4.k.1'],
        'medicinalproduct' => ['title' => 'Characterization of drug role' , 'element' => 'B.4.k.2.1'],
        'summary' => ['title' => 'Narrative case summary and further information' , 'element' => 'B.5'],
        'narrativeincludeclinical' => ['title' => 'Case narrative including clinical course,<br> therapeutic measures, outcome and additional relevant information' , 'element' => 'B.5.1'],

    ],



    'elementsLkp' => [
        'reporttype' => [1 => 'Spontaneous' , 2 => 'Report from study' , 3 => 'Other' , 4 => 'Not available to sender'],
        'serious' => [1 => 'Yes' , 2 => 'No'],
        'seriousnessdeath' => [1 => 'Yes' , 2 => 'No'],
        'seriousnesslifethreatening' => [1 => 'Yes' , 2 => 'No'],
        'seriousnesshospitalization' => [1 => 'Yes' , 2 => 'No'],
        'seriousnessdisabling' => [1 => 'Yes' , 2 => 'No'],
        'seriousnesscongenitalanomali' => [1 => 'Yes' , 2 => 'No'],
        'seriousnessother' => [ 1 => 'Yes' , 2 => 'No'],
        'qualification' => [ 1 => 'Physician' , 2 => 'Pharmacist' , 3 => 'Other Health Professional' , 4 => 'Lawyer' , 5 => 'Consumer or other non health professional'],
        'sendertype' => [1 => 'Pharmaceutical' , 2 => 'Regulatory Authority' , 3 => 'Health professional' , 4 => 'Regional Pharmacovigilance Center' , 5 => 'WHO Collaborating Center for International Drug Monitoring' , 6 => 'Other'],
        'patientonsetageunit' => [800 => 'Decade' , 801 => 'Year' , 802 => 'Month' , 803 => 'Week' , 804 => 'Day' , 805 => 'Hour'],
        'reactionstartdateformat' => [102 => 'CCYYMMDD' , 203 => 'CYYMMDDHHMM' ,610 => 'CCYYMM' , 602 => 'CCYY' ],
        'reactionenddateformat' => [102 => 'CCYYMMDD' , 203 => 'CYYMMDDHHMM' ,610 => 'CCYYMM' , 602 => 'CCYY' ],
        'reactionoutcome' => [1 => 'recovered/resolved' , 2 => 'recovering/resolving' , 3 => 'not recovered/not resolved' , 4 => 'recovered/resolved with sequelae' , 5 => 'fatal' , 6 => 'unknown'],
        'drugcharacterization' => [1 => 'Suspect' , 2 => 'Concomitant' , 3 => 'Interacting'],

    ],

    'Roles' =>[
        'Manager' ,'Qppv Person', 'Qppv Deputy', 'Guest'
    ]

];
