<?php
namespace backend\modules\crud\overrides\TrailChild;

use bedezign\yii2\audit\models\AuditTrail;
use backend\modules\crud\models\User;
use yii\helpers\StringHelper;

class AuditTrailChild extends AuditTrail{

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

        $this->model = StringHelper::basename($this->model);

        $this->user_id = $this->userIdentifierCallback($this->user_id);
        $this->model_id = $this->checkAndGetIcsrEventModelId($this->model_id);

    }


   private function userIdentifierCallback($id)
    {
        $user = User::findOne($id);

        return $user ? $user->username : $id;
    }

    //example on stored json object ... we need id only
    // {"id":25,"icsr_id":"41"}
    private function checkAndGetIcsrEventModelId ($jsonObject)
    {
        $decodedObject = json_decode($jsonObject);
        if (isset($decodedObject->id) && !empty($decodedObject->id))
        {
            return $decodedObject->id;
        }

        return $jsonObject;
    }


}