<?php
namespace backend\modules\crud\overrides\TrailChild;

use bedezign\yii2\audit\models\AuditTrail;

class AuditTrailChild extends AuditTrail{

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->model = str_replace('\\', '/', $this->model);
         $this->model = basename($this->model);
    }
}