<?php
/**
 * /var/www/html/yiiyak/console/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\jui\DatePicker;

/**
 *
 * @var yii\web\View $this
 * @var backend\modules\crud\models\IcsrOutcome $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="icsr-outcome-form">

    <?php $form = ActiveForm::begin([
		'id' => 'IcsrOutcome',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-error'
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
                    <?php 
                    echo       Html::activeHiddenInput($model, 'icsr_id') ;
                    ?>

			<?php echo // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'icsr_outcome_lkp_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(backend\modules\crud\models\LkpIcsrOutcome::find()->all(), 'id', 'description'),
	['prompt' => Yii::t('app', 'Select')]
); ?>
			        <?php echo $form->field($model, 'icsr_outcome_date')->widget(DatePicker::className(),['dateFormat' => 'yyyy-MM-dd']); ?>

         </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [ [
				'label'   => $model->getAliasModel(),
				'content' => $this->blocks['main'],
				'active'  => true,
			], ]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
