<?php
/**
 * /var/www/html/yiiyak/console/runtime/giiant/d4b4964a63cc95065fa0ae19074007ee
 *
 * @package default
 */


use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var backend\modules\crud\models\Drug $model
 */
$copyParams = $model->attributes;

$this->title = $model->getAliasModel() . $model->id;
$this->params['breadcrumbs'][] = ['label' => $model->getAliasModel(true), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud drug-view">

    <!-- flash message -->
    <?php 
    
    if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?php echo \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
              <?php echo $model->trade_name ?>        
    </h1>


    <div class="clearfix crud-navigation">
        <!-- menu buttons -->
        <div class='pull-left'>
            <?php echo Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
            <?php echo Html::a('<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('app', 'Copy'), ['create', 'id' => $model->id, 'Drug            '=>$copyParams], ['class' => 'btn btn-success']) ?>
            <?php echo Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
        </div>
        <div class="pull-right">
            <?php echo Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>


    <?php $this->beginBlock('backend\modules\crud\models\Drug'); ?>


    <?php echo DetailView::widget([
		'model' => $model,
		'attributes' => [
			'id',
			'generic_name',
			'trade_name',
			'composition',
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'company_id',
				'value' => ($model->getCompany()->one() ? Html::a($model->getCompany()->one()->name, ['/crud/company/view', 'id' => $model->getCompany()->one()->id, ]) : '<span class="label label-warning">?</span>'),
			],
			'manufacturer',
			'strength',
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'route_lkp_id',
				//'value' => ($model->getRouteLkp()->one() ? Html::a($model->getRouteLkp()->one()->id, ['/crud/lkp-route/view', 'id' => $model->getRouteLkp()->one()->id, ]) : '<span class="label label-warning">?</span>'),
                            'value' => ($model->getRouteLkp()->one() ?  $model->getRouteLkp()->one()->description : '<span class="label label-warning">?</span>'),
			],
		],
	]); ?>


    <hr/>


    <?php $this->endBlock(); ?>





<?php $this->beginBlock('Icsrs'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>

  <?php echo Html::a(
	'<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' Icsr',
	['/crud/icsr/create', 'Icsr' => ['drug_id' => $model->id]],
	['class'=>'btn btn-success btn-xs']
); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-Icsrs', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Icsrs ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?php echo '<div class="table-responsive">' . \yii\grid\GridView::widget([
		'layout' => '{summary}{pager}<br/>{items}{pager}',
		'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getIcsrs(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-icsrs']]),
		'pager'        => [
			'class'          => yii\widgets\LinkPager::className(),
			'firstPageLabel' => Yii::t('app', 'First'),
			'lastPageLabel'  => Yii::t('app', 'Last')
		],
		'columns' => [[
				'class'      => 'yii\grid\ActionColumn',
				'template'   => '{view} {update}',
				'contentOptions' => ['nowrap'=>'nowrap'],

				/**
				 *
				 */
				'urlCreator' => function ($action, $model, $key, $index) {
					// using the column name as key, not mapping to 'id' like the standard generator
					$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
					$params[0] = '/crud/icsr' . '/' . $action;
					return $params;
				},
				'buttons'    => [

				],
				'controller' => '/crud/icsr'
			],
			'id',
			'patient_identifier',
			'patient_age',
			'patient_age_unit',
			'patient_birth_date',
			'patient_weight',
			'patient_weight_unit',
			'extra_history',
		]
	]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?php echo Tabs::widget(
	[
		'id' => 'relation-tabs',
		'encodeLabels' => false,
		'items' => [ [
				'label'   => '<b class=""># '.$model->id. '</b>',
				'content' => $this->blocks['backend\modules\crud\models\Drug'],
				'active'  => true,
			],  [
				'content' => $this->blocks['Icsrs'],
				'label'   => '<small>Icsrs <span class="badge badge-default">'.count($model->getIcsrs()->asArray()->all()).'</span></small>',
				'active'  => false,
			], ]
	]
);
?>
</div>
