<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "drug_prescription".
 *
 * @property integer $id
 * @property integer $drug_id
 * @property integer $icsr_id
 * @property string $dose
 * @property integer $frequency_lkp_id
 * @property string $expiration_date
 * @property string $lot_no
 * @property string $use_date_start
 * @property string $use_date_end
 * @property string $duration_of_use
 * @property string $duration_of_use_unit
 * @property string $reason_of_use
 * @property string $problem_went_after_stop
 * @property string $problem_returned_after_reuse
 * @property string $product_avilable
 * @property string $active_substance_names
 * @property string $drug_role
 * @property string $drug_addtional_info
 * @property boolean $drug_action_drug_withdrawn
 * @property boolean $drug_action_dose_reduced
 * @property boolean $drug_action_dose_increased
 * @property boolean $drug_action_dose_not_changed
 * @property boolean $drug_action_unknown
 *
 * @property \backend\modules\crud\models\Drug $drug
 * @property \backend\modules\crud\models\Icsr $icsr
 * @property \backend\modules\crud\models\LkpFrequency $frequencyLkp
 * @property string $aliasModel
 */
abstract class DrugPrescription extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const DURATION_OF_USE_UNIT_DAY = 'day';
    const DURATION_OF_USE_UNIT_WEEK = 'week';
    const DURATION_OF_USE_UNIT_MONTH = 'month';
    const PROBLEM_WENT_AFTER_STOP_YES = 'yes';
    const PROBLEM_WENT_AFTER_STOP_NO = 'no';
    const PROBLEM_RETURNED_AFTER_REUSE_YES = 'yes';
    const PROBLEM_RETURNED_AFTER_REUSE_NO = 'no';
    const PRODUCT_AVILABLE_YES = 'yes';
    const PRODUCT_AVILABLE_NO = 'no';
    const DRUG_ROLE_SUSPECT = 'Suspect';
    const DRUG_ROLE_CONCOMITANT = 'Concomitant';
    const DRUG_ROLE_INTERACTING = 'Interacting';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'drug_prescription';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'DrugPrescriptions');
        }else{
            return Yii::t('app', 'DrugPrescription');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['drug_id', 'icsr_id', 'frequency_lkp_id'], 'integer'],
            [['icsr_id'], 'required'],
            [['expiration_date', 'use_date_start', 'use_date_end'], 'safe'],
            [['duration_of_use'], 'number'],
            [['duration_of_use_unit', 'problem_went_after_stop', 'problem_returned_after_reuse', 'product_avilable', 'drug_role'], 'string'],
            [['drug_action_drug_withdrawn', 'drug_action_dose_reduced', 'drug_action_dose_increased', 'drug_action_dose_not_changed', 'drug_action_unknown'], 'boolean'],
            [['dose', 'lot_no'], 'string', 'max' => 45],
            [['reason_of_use'], 'string', 'max' => 60],
            [['active_substance_names', 'drug_addtional_info'], 'string', 'max' => 450],
            [['drug_id'], 'exist', 'skipOnError' => true, 'targetClass' => Drug::className(), 'targetAttribute' => ['drug_id' => 'id']],
            [['icsr_id'], 'exist', 'skipOnError' => true, 'targetClass' => Icsr::className(), 'targetAttribute' => ['icsr_id' => 'id']],
            [['frequency_lkp_id'], 'exist', 'skipOnError' => true, 'targetClass' => LkpFrequency::className(), 'targetAttribute' => ['frequency_lkp_id' => 'id']],
            ['duration_of_use_unit', 'in', 'range' => [
                    self::DURATION_OF_USE_UNIT_DAY,
                    self::DURATION_OF_USE_UNIT_WEEK,
                    self::DURATION_OF_USE_UNIT_MONTH,
                ]
            ],
            ['problem_went_after_stop', 'in', 'range' => [
                    self::PROBLEM_WENT_AFTER_STOP_YES,
                    self::PROBLEM_WENT_AFTER_STOP_NO,
                ]
            ],
            ['problem_returned_after_reuse', 'in', 'range' => [
                    self::PROBLEM_RETURNED_AFTER_REUSE_YES,
                    self::PROBLEM_RETURNED_AFTER_REUSE_NO,
                ]
            ],
            ['product_avilable', 'in', 'range' => [
                    self::PRODUCT_AVILABLE_YES,
                    self::PRODUCT_AVILABLE_NO,
                ]
            ],
            ['drug_role', 'in', 'range' => [
                    self::DRUG_ROLE_SUSPECT,
                    self::DRUG_ROLE_CONCOMITANT,
                    self::DRUG_ROLE_INTERACTING,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'drug_id' => Yii::t('app', 'Drug ID'),
            'icsr_id' => Yii::t('app', 'Icsr ID'),
            'dose' => Yii::t('app', 'Dose'),
            'frequency_lkp_id' => Yii::t('app', 'Frequency Lkp ID'),
            'expiration_date' => Yii::t('app', 'Expiration Date'),
            'lot_no' => Yii::t('app', 'Lot No'),
            'use_date_start' => Yii::t('app', 'Use Date Start'),
            'use_date_end' => Yii::t('app', 'Use Date End'),
            'duration_of_use' => Yii::t('app', 'Duration Of Use'),
            'duration_of_use_unit' => Yii::t('app', 'Duration Of Use Unit'),
            'reason_of_use' => Yii::t('app', 'Reason Of Use'),
            'problem_went_after_stop' => Yii::t('app', 'Problem Went After Stop'),
            'problem_returned_after_reuse' => Yii::t('app', 'Problem Returned After Reuse'),
            'product_avilable' => Yii::t('app', 'Product Avilable'),
            'active_substance_names' => Yii::t('app', 'Active Substance Names'),
            'drug_role' => Yii::t('app', 'Drug Role'),
            'drug_addtional_info' => Yii::t('app', 'Drug Addtional Info'),
            'drug_action_drug_withdrawn' => Yii::t('app', 'Drug Action Drug Withdrawn'),
            'drug_action_dose_reduced' => Yii::t('app', 'Drug Action Dose Reduced'),
            'drug_action_dose_increased' => Yii::t('app', 'Drug Action Dose Increased'),
            'drug_action_dose_not_changed' => Yii::t('app', 'Drug Action Dose Not Changed'),
            'drug_action_unknown' => Yii::t('app', 'Drug Action Unknown'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('app', 'ID'),
            'drug_id' => Yii::t('app', 'Drug Id'),
            'icsr_id' => Yii::t('app', 'Icsr Id'),
            'dose' => Yii::t('app', '	B.4.k.6 Dosage text (e.g., 2 mg three times a day for five days)
'),
            'frequency_lkp_id' => Yii::t('app', 'Frequency Lkp Id'),
            'expiration_date' => Yii::t('app', 'Expiration Date'),
            'lot_no' => Yii::t('app', '	B.4.k.3 Batch/lot number
'),
            'use_date_start' => Yii::t('app', 'B.4.k.12 Date of start of drug'),
            'use_date_end' => Yii::t('app', '	B.4.k.14 Date of last administration
'),
            'duration_of_use' => Yii::t('app', '	B.4.k.15 Duration of drug administration
'),
            'duration_of_use_unit' => Yii::t('app', '	B.4.k.15 Duration of drug administration
'),
            'reason_of_use' => Yii::t('app', '	B.4.k.11 Indication for use in the case
'),
            'problem_went_after_stop' => Yii::t('app', 'Problem Went After Stop'),
            'problem_returned_after_reuse' => Yii::t('app', '	B.4.k.17 Effect of rechallenge
'),
            'product_avilable' => Yii::t('app', 'Product Avilable'),
            'active_substance_names' => Yii::t('app', 'B.4.k.2.2 Active substance name(s)

'),
            'drug_role' => Yii::t('app', 'B.4.k.1 Characterization of drug role (Suspect/Concomitant/Interacting)'),
            'drug_addtional_info' => Yii::t('app', 'B.4.k.19 Additional information on drug
'),
            'drug_action_drug_withdrawn' => Yii::t('app', 'B.4.k.16 Action(s) taken with drug'),
            'drug_action_dose_reduced' => Yii::t('app', 'B.4.k.16 Action(s) taken with drug'),
            'drug_action_dose_increased' => Yii::t('app', 'B.4.k.16 Action(s) taken with drug'),
            'drug_action_dose_not_changed' => Yii::t('app', 'B.4.k.16 Action(s) taken with drug'),
            'drug_action_unknown' => Yii::t('app', 'B.4.k.16 Action(s) taken with drug'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDrug()
    {
        return $this->hasOne(\backend\modules\crud\models\Drug::className(), ['id' => 'drug_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIcsr()
    {
        return $this->hasOne(\backend\modules\crud\models\Icsr::className(), ['id' => 'icsr_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFrequencyLkp()
    {
        return $this->hasOne(\backend\modules\crud\models\LkpFrequency::className(), ['id' => 'frequency_lkp_id']);
    }




    /**
     * get column duration_of_use_unit enum value label
     * @param string $value
     * @return string
     */
    public static function getDurationOfUseUnitValueLabel($value){
        $labels = self::optsDurationOfUseUnit();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column duration_of_use_unit ENUM value labels
     * @return array
     */
    public static function optsDurationOfUseUnit()
    {
        return [
            self::DURATION_OF_USE_UNIT_DAY => Yii::t('app', self::DURATION_OF_USE_UNIT_DAY),
            self::DURATION_OF_USE_UNIT_WEEK => Yii::t('app', self::DURATION_OF_USE_UNIT_WEEK),
            self::DURATION_OF_USE_UNIT_MONTH => Yii::t('app', self::DURATION_OF_USE_UNIT_MONTH),
        ];
    }

    /**
     * get column problem_went_after_stop enum value label
     * @param string $value
     * @return string
     */
    public static function getProblemWentAfterStopValueLabel($value){
        $labels = self::optsProblemWentAfterStop();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column problem_went_after_stop ENUM value labels
     * @return array
     */
    public static function optsProblemWentAfterStop()
    {
        return [
            self::PROBLEM_WENT_AFTER_STOP_YES => Yii::t('app', self::PROBLEM_WENT_AFTER_STOP_YES),
            self::PROBLEM_WENT_AFTER_STOP_NO => Yii::t('app', self::PROBLEM_WENT_AFTER_STOP_NO),
        ];
    }

    /**
     * get column problem_returned_after_reuse enum value label
     * @param string $value
     * @return string
     */
    public static function getProblemReturnedAfterReuseValueLabel($value){
        $labels = self::optsProblemReturnedAfterReuse();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column problem_returned_after_reuse ENUM value labels
     * @return array
     */
    public static function optsProblemReturnedAfterReuse()
    {
        return [
            self::PROBLEM_RETURNED_AFTER_REUSE_YES => Yii::t('app', self::PROBLEM_RETURNED_AFTER_REUSE_YES),
            self::PROBLEM_RETURNED_AFTER_REUSE_NO => Yii::t('app', self::PROBLEM_RETURNED_AFTER_REUSE_NO),
        ];
    }

    /**
     * get column product_avilable enum value label
     * @param string $value
     * @return string
     */
    public static function getProductAvilableValueLabel($value){
        $labels = self::optsProductAvilable();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column product_avilable ENUM value labels
     * @return array
     */
    public static function optsProductAvilable()
    {
        return [
            self::PRODUCT_AVILABLE_YES => Yii::t('app', self::PRODUCT_AVILABLE_YES),
            self::PRODUCT_AVILABLE_NO => Yii::t('app', self::PRODUCT_AVILABLE_NO),
        ];
    }

    /**
     * get column drug_role enum value label
     * @param string $value
     * @return string
     */
    public static function getDrugRoleValueLabel($value){
        $labels = self::optsDrugRole();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column drug_role ENUM value labels
     * @return array
     */
    public static function optsDrugRole()
    {
        return [
            self::DRUG_ROLE_SUSPECT => Yii::t('app', self::DRUG_ROLE_SUSPECT),
            self::DRUG_ROLE_CONCOMITANT => Yii::t('app', self::DRUG_ROLE_CONCOMITANT),
            self::DRUG_ROLE_INTERACTING => Yii::t('app', self::DRUG_ROLE_INTERACTING),
        ];
    }

}
