<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "icsr_version_response".
 *
 * @property integer $id
 * @property integer $icsr_version_id
 * @property string $response
 * @property string $response_date
 * @property string $aliasModel
 */
abstract class IcsrVersionResponse extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'icsr_version_response';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['icsr_version_id','response'], 'required'],
            [['icsr_version_id'], 'integer'],
            [['response_date'], 'safe'],
            [['response'], 'string', 'max' => 255],
            [['icsr_version_id'], 'exist', 'skipOnError' => true, 'targetClass' => IcsrVersion::className(), 'targetAttribute' => ['icsr_version_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'icsr_version_id' => 'Icsr Version ID',
            'response' => 'Response',
            'response_date' => 'Response Date',
        ];
    }




}
