<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "icsr_narritive".
 *
 * @property integer $id
 * @property integer $icsr_id
 * @property string $narritive
 * @property string $reporter_comment
 * @property string $sender_comment
 * @property string $aliasModel
 */
abstract class IcsrNarritive extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'icsr_narritive';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['icsr_id'], 'required'],
            [['icsr_id'], 'integer'],
            [['narritive'], 'string', 'max' => 20000],
            [['reporter_comment'], 'string', 'max' => 500],
            [['sender_comment'], 'string', 'max' => 2000],
            [['icsr_id'], 'exist', 'skipOnError' => true, 'targetClass' => Icsr::className(), 'targetAttribute' => ['icsr_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'icsr_id' => 'Icsr ID',
            'narritive' => 'Narrative',
            'reporter_comment' => 'Reporter Comment',
            'sender_comment' => 'Sender Comment',
        ];
    }


    public function attributeHints()
    {
    return [

        'narritive' => Yii::t('app','B.5.1 Case narrative including clinical course, therapeutic measures, outcome and additional relevant information'),
        'reporter_comment' => Yii::t('app',"B.5.2 Reporter's comments"),
        'sender_comment' => Yii::t('app',"B.5.4 Sender's comments")
        ];
    }



}
