<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "icsr_version".
 *
 * @property integer $id
 * @property integer $icsr_id
 * @property string $file_name
 * @property string $file_url
 * @property string $aliasModel
 */
abstract class IcsrVersion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'icsr_version';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['icsr_id','file_url'], 'required'],
            [['icsr_id'], 'integer'],
            [['file_name', 'file_url'], 'string', 'max' => 255],
            [['icsr_id'], 'exist', 'skipOnError' => true, 'targetClass' => Icsr::className(), 'targetAttribute' => ['icsr_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'icsr_id' => 'Icsr ID',
            'file_name' => 'File Name',
            'file_url' => 'File ',
        ];
    }




}
