<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "lkp_icsr_outcome".
 *
 * @property integer $id
 * @property string $description
 *
 * @property \backend\modules\crud\models\IcsrOutcome[] $icsrOutcomes
 * @property \backend\modules\crud\models\Icsr[] $icsrs
 * @property string $aliasModel
 */
abstract class LkpIcsrOutcome extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lkp_icsr_outcome';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'LkpIcsrOutcomes');
        }else{
            return Yii::t('app', 'LkpIcsrOutcome');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'integer'],
            [['description'], 'string', 'max' => 512]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('app', 'ID'),
            'description' => Yii::t('app', ' Death (include date) 
 Life-Threatening 
 Hospitalization (Initial or Prolonged) 
 Disability or Permanent Damage
 Congenital Anomaly/Birth Defect 
 Required Intervention to Prevent Permanent Impairment/Damage (Devices) 
 Other Serious (Important Medical Events) '),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIcsrOutcomes()
    {
        return $this->hasMany(\backend\modules\crud\models\IcsrOutcome::className(), ['icsr_outcome_lkp_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIcsrs()
    {
        return $this->hasMany(\backend\modules\crud\models\Icsr::className(), ['id' => 'icsr_id'])->viaTable('icsr_outcome', ['icsr_outcome_lkp_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\crud\models\query\LkpIcsrOutcomeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\crud\models\query\LkpIcsrOutcomeQuery(get_called_class());
    }


}
