<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "lkp_icsr_type".
 *
 * @property integer $id
 * @property string $description
 *
 * @property \backend\modules\crud\models\IcsrType[] $icsrTypes
 * @property \backend\modules\crud\models\Icsr[] $icsrs
 * @property string $aliasModel
 */
abstract class LkpIcsrType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lkp_icsr_type';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'LkpIcsrTypes');
        }else{
            return Yii::t('app', 'LkpIcsrType');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
 
            [['id'], 'integer'],
            [['description'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('app', 'ID'),
            'description' => Yii::t('app', 'Adverse Event
 Product Use Error
 Product Problem (Example: Defects/Malfunctions) 
 Problem with Different Manufacturer of the Same Medicine'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIcsrTypes()
    {
        return $this->hasMany(\backend\modules\crud\models\IcsrType::className(), ['icsr_type_lkp_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIcsrs()
    {
        return $this->hasMany(\backend\modules\crud\models\Icsr::className(), ['id' => 'icsr_id'])->viaTable('icsr_type', ['icsr_type_lkp_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\crud\models\query\LkpIcsrTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\crud\models\query\LkpIcsrTypeQuery(get_called_class());
    }


}
