<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "lkp_limits".
 *
 * @property integer $id
 * @property string $name
 * @property string $aliasModel
 */
abstract class LkpLimits extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lkp_limits';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }


public function getPlans ()
{
    return $this->hasMany(\backend\modules\crud\models\LkpPlan::className(),['id' => 'plan_id'])->viaTable('plan_limits',['limit_id' => 'id']);
}

}
