<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "lkp_meddra_pt".
 *
 * @property integer $id
 * @property string $code
 * @property string $description
 * @property integer $meddra_hlgt_id
 *
 * @property \backend\modules\crud\models\IcsrEvent[] $icsrEvents
 * @property \backend\modules\crud\models\LkpMeddraLlt[] $lkpMeddraLlts
 * @property \backend\modules\crud\models\LkpMeddraHlgt $meddraHlgt
 * @property string $aliasModel
 */
abstract class LkpMeddraPt extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lkp_meddra_pt';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'LkpMeddraPts');
        }else{
            return Yii::t('app', 'LkpMeddraPt');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'meddra_hlgt_id'], 'required'],
            [['id', 'meddra_hlgt_id'], 'integer'],
            [['code', 'description'], 'string', 'max' => 45],
            [['meddra_hlgt_id'], 'exist', 'skipOnError' => true, 'targetClass' => LkpMeddraHlgt::className(), 'targetAttribute' => ['meddra_hlgt_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'code' => Yii::t('app', 'Code'),
            'description' => Yii::t('app', 'Description'),
            'meddra_hlgt_id' => Yii::t('app', 'Meddra Hlgt ID'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('app', 'ID'),
            'code' => Yii::t('app', 'Code'),
            'description' => Yii::t('app', 'Description'),
            'meddra_hlgt_id' => Yii::t('app', 'Meddra Hlgt Id'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIcsrEvents()
    {
        return $this->hasMany(\backend\modules\crud\models\IcsrEvent::className(), ['meddra_pt_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLkpMeddraLlts()
    {
        return $this->hasMany(\backend\modules\crud\models\LkpMeddraLlt::className(), ['meddra_pt_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeddraHlgt()
    {
        return $this->hasOne(\backend\modules\crud\models\LkpMeddraHlgt::className(), ['id' => 'meddra_hlgt_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\crud\models\query\LkpMeddraPtQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\crud\models\query\LkpMeddraPtQuery(get_called_class());
    }


}
