<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "lkp_meddra_hlgt".
 *
 * @property integer $id
 * @property string $code
 * @property string $description
 *
 * @property \backend\modules\crud\models\LkpMeddraPt[] $lkpMeddraPts
 * @property string $aliasModel
 */
abstract class LkpMeddraHlgt extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lkp_meddra_hlgt';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'LkpMeddraHlgts');
        }else{
            return Yii::t('app', 'LkpMeddraHlgt');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['code', 'description'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'code' => Yii::t('app', 'Code'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('app', 'ID'),
            'code' => Yii::t('app', 'Code'),
            'description' => Yii::t('app', 'Description'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLkpMeddraPts()
    {
        return $this->hasMany(\backend\modules\crud\models\LkpMeddraPt::className(), ['meddra_hlgt_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\crud\models\query\LkpMeddraHlgtQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\crud\models\query\LkpMeddraHlgtQuery(get_called_class());
    }


}
