<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "lkp_test".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 *
 * @property \backend\modules\crud\models\IcsrTest[] $icsrTests
 * @property string $aliasModel
 */
abstract class LkpTest extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lkp_test';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'LkpTests');
        }else{
            return Yii::t('app', 'LkpTest');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'integer'],
            [['name', 'description'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIcsrTests()
    {
        return $this->hasMany(\backend\modules\crud\models\IcsrTest::className(), ['test_lkp_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\crud\models\query\LkpTestQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\crud\models\query\LkpTestQuery(get_called_class());
    }


}
