<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "meddra_smq_list".
 *
 * @property string $id
 * @property string $name
 * @property integer $level
 * @property string $description
 * @property string $source
 * @property string $note
 * @property string $meddra_version
 * @property string $status
 * @property string $algorithm
 * @property string $aliasModel
 */
abstract class MeddraSmqList extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'meddra_smq_list';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'name', 'level', 'description', 'meddra_version', 'status', 'algorithm'], 'required'],
            [['id', 'level'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['description', 'source', 'note'], 'string', 'max' => 2000],
            [['meddra_version'], 'string', 'max' => 5],
            [['status'], 'string', 'max' => 1],
            [['algorithm'], 'string', 'max' => 1000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'level' => 'Level',
            'description' => 'Description',
            'source' => 'Source',
            'note' => 'Note',
            'meddra_version' => 'Meddra Version',
            'status' => 'Status',
            'algorithm' => 'Algorithm',
        ];
    }




}
