<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "meddra_soc_hlgt".
 *
 * @property string $soc_id
 * @property string $hlgt_id
 * @property string $aliasModel
 */
abstract class MeddraSocHlgt extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'meddra_soc_hlgt';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['soc_id', 'hlgt_id'], 'required'],
            [['soc_id', 'hlgt_id'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'soc_id' => 'Soc ID',
            'hlgt_id' => 'Hlgt ID',
        ];
    }




}
