<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "meddra_hlt_pt".
 *
 * @property string $hlt_id
 * @property string $pt_id
 * @property string $aliasModel
 */
abstract class MeddraHltPt extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'meddra_hlt_pt';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hlt_id', 'pt_id'], 'required'],
            [['hlt_id', 'pt_id'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'hlt_id' => 'Hlt ID',
            'pt_id' => 'Pt ID',
        ];
    }




}
