<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "meddra_mdhier".
 *
 * @property integer $id
 * @property string $pt_id
 * @property string $hlt_id
 * @property string $hlgt_id
 * @property string $soc_id
 * @property string $pt_term
 * @property string $hlt_term
 * @property string $hlgt_term
 * @property string $soc_term
 * @property string $soc_abbrev
 * @property string $null_field
 * @property string $pt_soc_id
 * @property string $primary_soc_fg
 * @property string $aliasModel
 */
abstract class MeddraMdhier extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'meddra_mdhier';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pt_id', 'hlt_id', 'hlgt_id', 'soc_id', 'pt_term', 'hlt_term', 'hlgt_term', 'soc_term', 'soc_abbrev'], 'required'],
            [['pt_id', 'hlt_id', 'hlgt_id', 'soc_id', 'pt_soc_id'], 'integer'],
            [['pt_term', 'hlt_term', 'hlgt_term', 'soc_term'], 'string', 'max' => 100],
            [['soc_abbrev'], 'string', 'max' => 5],
            [['null_field', 'primary_soc_fg'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pt_id' => 'Pt ID',
            'hlt_id' => 'Hlt ID',
            'hlgt_id' => 'Hlgt ID',
            'soc_id' => 'Soc ID',
            'pt_term' => 'Pt Term',
            'hlt_term' => 'Hlt Term',
            'hlgt_term' => 'Hlgt Term',
            'soc_term' => 'Soc Term',
            'soc_abbrev' => 'Soc Abbrev',
            'null_field' => 'Null Field',
            'pt_soc_id' => 'Pt Soc ID',
            'primary_soc_fg' => 'Primary Soc Fg',
        ];
    }




}
