<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;


/**
 * This is the base-model class for table "psmf_section".
 *
 * @property integer $id
 * @property integer $psmf_id
 * @property string $section_name
 * @property string $section_content
 * @property string $aliasModel
 */
abstract class PsmfSection extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'psmf_section';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['psmf_id','section_name','section_content'], 'required'],
            [['psmf_id'], 'integer'],
            [['section_content'], 'string'],
            [['section_name'], 'string', 'max' => 255],
            [['psmf_id'], 'exist', 'skipOnError' => true, 'targetClass' => PsmfCompany::className(), 'targetAttribute' => ['psmf_id' => 'psmf_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'psmf_id' => 'Psmf ID',
            'section_name' => 'Section Name',
            'section_content' => 'Section Content',
        ];
    }




}
