<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "rmp".
 *
 * @property integer $id
 * @property integer $drug_id
 * @property string $version
 * @property string $version_description
 * @property string $rmp_file_url
 * @property string $ack_file_url
 * @property integer $prsu_created_by
 * @property string $prsu_created_at
 * @property integer $ack_created_by
 * @property string $ack_created_at
 * @property string $aliasModel
 */
abstract class Rmp extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rmp';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['drug_id', 'prsu_created_by'], 'required'],
            [['drug_id', 'prsu_created_by', 'ack_created_by'], 'integer'],
            [['version'], 'number'],
            [['prsu_created_at', 'ack_created_at'], 'safe'],
            [['version_description', 'rmp_file_url', 'ack_file_url'], 'string', 'max' => 255],
            [['drug_id'], 'exist', 'skipOnError' => true, 'targetClass' => Drug::className(), 'targetAttribute' => ['drug_id' => 'id']],
            [['prsu_created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['prsu_created_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'drug_id' => 'Drug ID',
            'version' => 'Version',
            'version_description' => 'Version Description',
            'rmp_file_url' => 'Rmp File Url',
            'ack_file_url' => 'Ack File Url',
            'prsu_created_by' => 'Prsu Created By',
            'prsu_created_at' => 'Prsu Created At',
            'ack_created_by' => 'Ack Created By',
            'ack_created_at' => 'Ack Created At',
        ];
    }




}
