<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use kartik\password\StrengthValidator;
use Yii;
use yii\db\Query;

/**
 * This is the base-model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \backend\modules\crud\models\UserCompany[] $userCompanies
 * @property \backend\modules\crud\models\Company[] $companies
 * @property string $aliasModel
 */
abstract class User extends \yii\db\ActiveRecord
{

    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'Users');
        }else{
            return Yii::t('app', 'User');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password_hash', 'email','company_id'], 'required'],
            [['status','company_id'], 'integer'],
            [['email'],'email'],
            [['username', 'password_hash', 'password_reset_token', 'email'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
            [['password_hash'], StrengthValidator::className(), 'min'=>8, 'digit'=>3 ,'upper' => 0 , 'special' => 0]

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'username' => Yii::t('app', 'Username'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'password_hash' => Yii::t('app', 'Password '),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'email' => Yii::t('app', 'Email'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'company_id' => Yii::t('app','Company')
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('app', 'ID'),
            'username' => Yii::t('app', 'Username'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'password_hash' => Yii::t('app', 'Password Hash'),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'email' => Yii::t('app', 'Email'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserCompanies()
    {
        return $this->hasMany(\backend\modules\crud\models\UserCompany::className(), ['user_id' => 'id']);
    }


    public function getAllCompanies()
    {
         return \backend\modules\crud\models\Company::find()->all();
    }

   /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\backend\modules\crud\models\Company::className(), ['id' => 'company_id']);
    }


    public function getRole ($user_id)
    {

        $query = new Query;

       return $query->select('item_name')
              ->from('auth_assignment')
              ->where(['user_id' => $user_id])
              ->one();

    }

    public function setRole ($user_id,$roleName)
    {

        return \Yii::$app->db->createCommand()->insert('auth_assignment',
                            ['user_id' => $user_id,'item_name' => $roleName]
                            )->execute();
    }

    public function updateRole ($user_id,$roleName)
    {
        if ($roleName == $this->getRole($user_id)['item_name'])
            return 1;

        return \Yii::$app->db->createCommand()->update('auth_assignment',

                    ['item_name' => $roleName] , 'user_id = '.$user_id
            )->execute();
    }
    
    /**
     * @inheritdoc
     * @return \backend\modules\crud\models\query\UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\crud\models\query\UserQuery(get_called_class());
    }



}
