<?php
/**
 * /var/www/html/yiiyak/console/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var backend\modules\crud\models\DrugPrescription $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="drug-prescription-form">

    <?php $form = ActiveForm::begin([
		'id' => 'DrugPrescription',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-error'
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

			<?php echo $form->field($model, 'id')->textInput() ?>
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'drug_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(backend\modules\crud\models\Drug::find()->all(), 'id', 'id'),
	['prompt' => Yii::t('app', 'Select')]
); ?>
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'icsr_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(backend\modules\crud\models\Icsr::find()->all(), 'id', 'id'),
	['prompt' => Yii::t('app', 'Select')]
); ?>
			<?php echo $form->field($model, 'dose')->textInput(['maxlength' => true]) ?>
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'frequency_lkp_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(backend\modules\crud\models\LkpFrequency::find()->all(), 'id', 'id'),
	['prompt' => Yii::t('app', 'Select')]
); ?>
			<?php echo $form->field($model, 'expiration_date')->textInput() ?>
			<?php echo $form->field($model, 'lot_no')->textInput(['maxlength' => true]) ?>
			<?php echo $form->field($model, 'ndc')->textInput(['maxlength' => true]) ?>
			<?php echo $form->field($model, 'use_date_start')->textInput() ?>
			<?php echo $form->field($model, 'use_date_end')->textInput() ?>
			<?php echo $form->field($model, 'duration_of_use')->textInput(['maxlength' => true]) ?>
			<?php echo                         $form->field($model, 'duration_of_use_unit')->dropDownList(
	backend\modules\crud\models\DrugPrescription::optsdurationofuseunit()
); ?>
			<?php echo $form->field($model, 'reason_of_use')->textInput(['maxlength' => true]) ?>
			<?php echo                         $form->field($model, 'problem_went_after_stop')->dropDownList(
	backend\modules\crud\models\DrugPrescription::optsproblemwentafterstop()
); ?>
			<?php echo                         $form->field($model, 'problem_returned_after_reuse')->dropDownList(
	backend\modules\crud\models\DrugPrescription::optsproblemreturnedafterreuse()
); ?>
			<?php echo                         $form->field($model, 'product_avilable')->dropDownList(
	backend\modules\crud\models\DrugPrescription::optsproductavilable()
); ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [ [
				'label'   => $model->getAliasModel(),
				'content' => $this->blocks['main'],
				'active'  => true,
			], ]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
