<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var backend\modules\crud\models\DrugPrescription $model
*/
$copyParams = $model->attributes;

$this->title = $model->getAliasModel() . $model->id;
$this->params['breadcrumbs'][] = ['label' => $model->getAliasModel(true), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud drug-prescription-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= $model->getAliasModel() ?>        <small>
            <?= $model->id ?>        </small>
    </h1>


    <div class="clearfix crud-navigation">
        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
            <?= Html::a('<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('app', 'Copy'), ['create', 'id' => $model->id, 'DrugPrescription            '=>$copyParams],['class' => 'btn btn-success']) ?>
            <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
        </div>
        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>


    <?php $this->beginBlock('backend\modules\crud\models\DrugPrescription'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'id',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'drug_id',
    'value' => ($model->getDrug()->one() ? Html::a($model->getDrug()->one()->id, ['drug/view', 'id' => $model->getDrug()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'icsr_id',
    'value' => ($model->getIcsr()->one() ? Html::a($model->getIcsr()->one()->id, ['icsr/view', 'id' => $model->getIcsr()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
        'dose',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'frequency_lkp_id',
    'value' => ($model->getFrequencyLkp()->one() ? Html::a($model->getFrequencyLkp()->one()->id, ['lkp-frequency/view', 'id' => $model->getFrequencyLkp()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
        'expiration_date',
        'lot_no',
        'use_date_start',
        'use_date_end',
        'duration_of_use',
            [
                'attribute'=>'duration_of_use_unit',
                'value'=>backend\modules\crud\models\DrugPrescription::getDurationOfUseUnitValueLabel($model->duration_of_use_unit),
            ],
        'reason_of_use',
            [
                'attribute'=>'problem_went_after_stop',
                'value'=>backend\modules\crud\models\DrugPrescription::getProblemWentAfterStopValueLabel($model->problem_went_after_stop),
            ],
            [
                'attribute'=>'problem_returned_after_reuse',
                'value'=>backend\modules\crud\models\DrugPrescription::getProblemReturnedAfterReuseValueLabel($model->problem_returned_after_reuse),
            ],
            [
                'attribute'=>'product_avilable',
                'value'=>backend\modules\crud\models\DrugPrescription::getProductAvilableValueLabel($model->product_avilable),
            ],
        'active_substance_names',
            [
                'attribute'=>'drug_role',
                'value'=>backend\modules\crud\models\DrugPrescription::getDrugRoleValueLabel($model->drug_role),
            ],
        'drug_addtional_info',
        'drug_action_drug_withdrawn:boolean',
        'drug_action_dose_reduced:boolean',
        'drug_action_dose_increased:boolean',
        'drug_action_dose_not_changed:boolean',
        'drug_action_unknown:boolean',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['backend\modules\crud\models\DrugPrescription'],
    'active'  => true,
], ]
                 ]
    );
    ?>
</div>
