<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\controllers\base;

use backend\modules\crud\models\Icsr;
    use backend\modules\crud\models\search\Icsr as IcsrSearch;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\StringHelper;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use dmstr\bootstrap\Tabs;
use yii\web\Response;

/**
* IcsrController implements the CRUD actions for Icsr model.
*/
class IcsrController extends Controller
{
/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = true;


/**
* Lists all Icsr models.
* @return mixed
*/
    public function actionIndex()
    {
        $searchModel  = new IcsrSearch;
        $dataProvider = $searchModel->search($_GET);

        Tabs::clearLocalStorage();

        Url::remember();
        \Yii::$app->session['__crudReturnUrl'] = null;

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

/**
* Displays a single Icsr model.
* @param integer $id
*
* @return mixed
*/
    public function actionView($id)
    {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $model = Icsr::find()->where(['id' => $id])->with('icsrVersions')->one();
            $versions = $this->maintainVersions($model->icsrVersions);
            $versionsCount = count($versions);
            return [
                'model'=>$model,
                'versions'=>$versions,
                'versionsCount'=>$versionsCount
            ];
        }
        \Yii::$app->session['__crudReturnUrl'] = Url::previous();
        Url::remember();
        Tabs::rememberActiveState();
        $model = $this->findModel($id);
        $signaledDrugs =  \Yii::$app->user->identity->company->getSignaledDrugs();
        $signaledIcsrsAndIcsrsEvents = $model->drug->getSignaledIcsrsAndIcsrEvenets($signaledDrugs);

        $isIcsrNullExported = $model->isNullExported();



       return $this->render('view', [
            'model' => $model,
            'signaledIcsrsAndIcsrsEvents' => $signaledIcsrsAndIcsrsEvents,
            'isIcsrNullExported' => $isIcsrNullExported
        ]);
    }

/**
* Creates a new Icsr model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
    public function actionCreate()
    {
        $model = new Icsr;

        try {
            if ($model->load($_POST) && $model->save()) {
                return $this->redirect(Url::previous());
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

/**
* Updates an existing Icsr model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id
* @return mixed
*/
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load($_POST) && $model->save()) {
            return $this->redirect(Url::previous());
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

/**
* Deletes an existing Icsr model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $id
* @return mixed
*/
    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            \Yii::$app->getSession()->addFlash('error', $msg);
            return $this->redirect(Url::previous());
        }

// TODO: improve detection
        $isPivot = strstr('$id',',');
        if ($isPivot == true) {
            return $this->redirect(Url::previous());
        } elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
            Url::remember(null);
            $url = \Yii::$app->session['__crudReturnUrl'];
            \Yii::$app->session['__crudReturnUrl'] = null;

            return $this->redirect($url);
        } else {
            return $this->redirect(['index']);
        }
    }

/**
* Finds the Icsr model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $id
* @return Icsr the loaded model
* @throws HttpException if the model cannot be found
*/
    protected function findModel($id)
    {
        if (($model = Icsr::findOne($id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }
    /**
     * @param $versions
     * take versions model versions
     * and maintain it for ajax call to be equal to crud
     * return object $versions
     **/
    private function maintainVersions($versions){
        $versions_array = [];
            $versions_array[] = ArrayHelper::toArray($versions, [
                'backend\modules\crud\models\IcsrVersion'=>[
                    'id',
                    'icsr_id',
                    'file_name',
                    'file_url',
                    'version_no',
                    'export_date',
                    'username'=>function($version){
                        return $version->user->username;
                    },
                    'response'=>function($version){
                        $url = '<a class="btn btn-warning btn-sm" href='. Yii::getAlias('@web').'/crud/icsr-version-response/create?icsr_version_id='
                            .$version->id.'&icsr_id='.$version->icsr_id.'> Choose Response Type </a>';
                        if (isset($version->icsrVersionResponse->response))
                        {
                            $bucket = Yii::$app->fileStorage->getBucket('icsrVersionsResponse');

                            $responseFileName = StringHelper::basename( $version->icsrVersionResponse->response);

                            if ($bucket->fileExists($responseFileName))
                            {
                                $url = "<a href={$version->icsrVersionResponse->response}> Response File </a>";
                            }
                            else{
                                return $version->icsrVersionResponse->response;

                            }
                        }

                        return $url;
                    },
                    'response_date'=>function($version){
                        if (isset($model->icsrVersionResponse->response_date)) {

                            return $version->icsrVersionResponse->response_date;
                        }
                        return Yii::t('app','response not received yet');
                    },
                    'send_href'=>function($version){

                        return Yii::getAlias('@web').'/crud/icsr-version/create-email?xmlUrl='
                            .$version->file_url.'&icsrId='.$version->icsr_id;
                    },
                ]
            ]);


         return $versions_array[0];

    }
}

