<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\controllers\base;

use backend\modules\crud\models\IcsrVersionResponse;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;
use yii\web\UploadedFile;

/**
* IcsrVersionResponseController implements the CRUD actions for IcsrVersionResponse model.
*/
class IcsrVersionResponseController extends Controller
{
/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Creates a new IcsrVersionResponse model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate($icsr_version_id,$icsr_id)
{
$model = new IcsrVersionResponse;
$model->icsr_version_id = $icsr_version_id;
try {


if ($model->load($_POST) ) {
    if (\Yii::$app->request->post('responseType') == 'file')
    {

        $model->xmlFile = UploadedFile::getInstance($model, 'xmlFile');

       if (! $model->upload())
       {
           \Yii::$app->getSession()->setFlash('error', 'The XML File not saved please try again later');
            return $this->redirect(\Yii::$app->request->referrer);
       }
    }

       if ($model->save())
       {
           return $this->redirect(['/crud/icsr/view?id='.$icsr_id]);
       }

} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}


/**
* Finds the IcsrVersionResponse model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $id
* @return IcsrVersionResponse the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($id)
{
if (($model = IcsrVersionResponse::findOne($id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
