<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\controllers\base;

use backend\modules\crud\models\IcsrEvent;
 use backend\modules\crud\models\search\IcsrEvent as IcsrEventSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use dmstr\bootstrap\Tabs;

/**
* IcsrEventController implements the CRUD actions for IcsrEvent model.
*/
class IcsrEventController extends Controller
{
/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;




/**
* Lists all IcsrEvent models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new IcsrEventSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}

/**
* Displays a single IcsrEvent model.
* @param integer $id
	 * @param integer $icsr_id
*
* @return mixed
*/
public function actionView($id, $icsr_id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($id, $icsr_id),
]);
}

/**
* Creates a new IcsrEvent model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new IcsrEvent;

try {
if ($model->load($_POST) && $model->save()) {

return $this->redirect(Url::previous());
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing IcsrEvent model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id
	 * @param integer $icsr_id
* @return mixed
*/
public function actionUpdate($id, $icsr_id)
{
$model = $this->findModel($id, $icsr_id);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing IcsrEvent model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $id
	 * @param integer $icsr_id
* @return mixed
*/
public function actionDelete($id, $icsr_id)
{
try {
$this->findModel($id, $icsr_id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$id, $icsr_id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the IcsrEvent model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $id
	 * @param integer $icsr_id
* @return IcsrEvent the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($id, $icsr_id)
{
if (($model = IcsrEvent::findOne(['id' => $id, 'icsr_id' => $icsr_id])) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
