<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "other_types".
 *
 * @property integer $id
 * @property integer $icsr_id
 * @property string $description
 * @property string $aliasModel
 */
 class Othertypes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'other_types';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'icsr_id', 'description'], 'required'],
            [['id', 'icsr_id'], 'integer'],
            [['description'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'icsr_id' => 'Icsr ID',
            'description' => 'Description',
        ];
    }




}
