<?php
/**
 * /var/www/html/yiiyak/console/runtime/giiant/d4b4964a63cc95065fa0ae19074007ee
 *
 * @package default
 */


use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var backend\modules\crud\models\Company $model
 */
$copyParams = $model->attributes;

$this->title = $model->getAliasModel() . $model->name;
$this->params['breadcrumbs'][] = ['label' => $model->getAliasModel(true), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud company-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?php echo \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?php echo $model->getAliasModel() ?>        <small>
            <?php echo $model->name ?>        </small>
    </h1>


    <div class="clearfix crud-navigation">
        <!-- menu buttons -->
        <div class='pull-left'>
            <?php echo Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
            <?php echo Html::a('<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('app', 'Copy'), ['create', 'id' => $model->id, 'Company            '=>$copyParams], ['class' => 'btn btn-success']) ?>
            <?php echo Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
        </div>


    </div>


    <?php $this->beginBlock('backend\modules\crud\models\Company'); ?>


    <?php echo DetailView::widget([
		'model' => $model,
		'attributes' => [
			[
				'attribute' => 'id',
				'value' => "PV-Company-" . hexdec($model->id / .2. "PVRadar")
			],
			'name',
			'adderess',
			'license_no',
			'license_image_url:url',
		],
	]); ?>


    <hr/>


    <?php $this->endBlock(); ?>






<?php $this->beginBlock('Users'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
		<a class="btn btn-success btn-xs" href="<?= Url::to(['/crud/user/create',  'Company' => ['company_id' => $model->id]])?>">

			<span class="glyphicon glyphicon-plus"></span>

			<?=  Yii::t('app','New User');?>

		</a>

</div></div><?php Pjax::begin(['id'=>'pjax-Users', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Users ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?php echo '<div class="table-responsive">' . \yii\grid\GridView::widget([
		'layout' => '{summary}{pager}<br/>{items}{pager}',
		'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getUsers(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-usercompanies']]),
		'pager'        => [
			'class'          => yii\widgets\LinkPager::className(),
			'firstPageLabel' => Yii::t('app', 'First'),
			'lastPageLabel'  => Yii::t('app', 'Last')
		],
		'columns' => [[
				'class'      => 'yii\grid\ActionColumn',
				'template'   => '{view} {update}',
				'contentOptions' => ['nowrap'=>'nowrap'],

				/**
				 *
				 */
				'urlCreator' => function ($action, $model, $key, $index) {
					// using the column name as key, not mapping to 'id' like the standard generator
					$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
					$params[0] = '/crud/user' . '/' . $action;
					return $params;
				},


			],

			[
				'class' => yii\grid\DataColumn::className(),
				'attribute' => 'id',

				/**
				 *
				 */
				'value' => function ($model,$key,$index) {
					$misleadingString = hexdec($model->id / .5 . "PVRadar");

					return "PV-User-{$misleadingString}" ;
				},
				'format' => 'raw',
			],
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
			[
				'class' => yii\grid\DataColumn::className(),
				'attribute' => 'user_name',

				/**
				 *
				 */
				'value' => function ($model) {
					return $model->username;
				},
				'format' => 'raw',
			],

		]
	]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?php echo Tabs::widget(
	[
		'id' => 'relation-tabs',
		'encodeLabels' => false,
		'items' => [ [
				'label'   => '<b class=""># '.$model->name.'</b>',
				'content' => $this->blocks['backend\modules\crud\models\Company'],
				'active'  => true,
			],  [
				'content' => $this->blocks['Users'],
				'label'   => '<small>Users <span class="badge badge-default">'.count($model->getUsers()->asArray()->all()).'</span></small>',
				'active'  => false,
			], ]
	]
);
?>
</div>
